// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Result {
    #[prost(enumeration = "Status", tag = "1")]
    pub status: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub fingerprint64: u64,
    #[prost(
        oneof = "result::Response",
        tags = "11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50"
    )]
    pub response: ::core::option::Option<result::Response>,
}
/// Nested message and enum types in `Result`.
pub mod result {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Response {
        #[prost(message, tag = "11")]
        TypeRes(super::TypeRes),
        #[prost(message, tag = "12")]
        PingRes(super::PingRes),
        #[prost(message, tag = "13")]
        EchoRes(super::EchoRes),
        #[prost(message, tag = "14")]
        HandshakeRes(super::HandshakeRes),
        #[prost(message, tag = "15")]
        ExistsRes(super::ExistsRes),
        #[prost(message, tag = "16")]
        GetRes(super::GetRes),
        #[prost(message, tag = "17")]
        SetRes(super::SetRes),
        #[prost(message, tag = "18")]
        DelRes(super::DelRes),
        #[prost(message, tag = "19")]
        KeysRes(super::KeysRes),
        #[prost(message, tag = "20")]
        GetdelRes(super::GetdelRes),
        #[prost(message, tag = "21")]
        GetexRes(super::GetexRes),
        #[prost(message, tag = "22")]
        GetsetRes(super::GetsetRes),
        #[prost(message, tag = "23")]
        IncrRes(super::IncrRes),
        #[prost(message, tag = "24")]
        DecrRes(super::DecrRes),
        #[prost(message, tag = "25")]
        IncrbyRes(super::IncrbyRes),
        #[prost(message, tag = "26")]
        DecrbyRes(super::DecrbyRes),
        #[prost(message, tag = "27")]
        FlushdbRes(super::FlushdbRes),
        #[prost(message, tag = "28")]
        ExpireRes(super::ExpireRes),
        #[prost(message, tag = "29")]
        ExpireatRes(super::ExpireatRes),
        #[prost(message, tag = "30")]
        ExpiretimeRes(super::ExpiretimeRes),
        #[prost(message, tag = "31")]
        TtlRes(super::TtlRes),
        #[prost(message, tag = "32")]
        GetwatchRes(super::GetwatchRes),
        #[prost(message, tag = "33")]
        UnwatchRes(super::UnwatchRes),
        #[prost(message, tag = "34")]
        HgetRes(super::HgetRes),
        #[prost(message, tag = "35")]
        HsetRes(super::HsetRes),
        #[prost(message, tag = "36")]
        HgetallRes(super::HgetallRes),
        #[prost(message, tag = "37")]
        HgetwatchRes(super::HgetwatchRes),
        #[prost(message, tag = "38")]
        HgetallwatchRes(super::HgetallwatchRes),
        #[prost(message, tag = "39")]
        ZaddRes(super::ZaddRes),
        #[prost(message, tag = "40")]
        ZcountRes(super::ZcountRes),
        #[prost(message, tag = "41")]
        ZrangeRes(super::ZrangeRes),
        #[prost(message, tag = "42")]
        ZpopmaxRes(super::ZpopmaxRes),
        #[prost(message, tag = "43")]
        ZremRes(super::ZremRes),
        #[prost(message, tag = "44")]
        ZpopminRes(super::ZpopminRes),
        #[prost(message, tag = "45")]
        ZrankRes(super::ZrankRes),
        #[prost(message, tag = "46")]
        ZcardRes(super::ZcardRes),
        #[prost(message, tag = "47")]
        ZrangewatchRes(super::ZrangewatchRes),
        #[prost(message, tag = "48")]
        ZcountwatchRes(super::ZcountwatchRes),
        #[prost(message, tag = "49")]
        ZcardwatchRes(super::ZcardwatchRes),
        #[prost(message, tag = "50")]
        ZrankwatchRes(super::ZrankwatchRes),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZrankwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HgetwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HgetallwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZaddRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZcountRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeRes {
    #[prost(string, tag = "1")]
    pub r#type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PingRes {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HgetRes {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HsetRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HElement {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HgetallRes {
    #[prost(message, repeated, tag = "1")]
    pub elements: ::prost::alloc::vec::Vec<HElement>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TtlRes {
    #[prost(int64, tag = "1")]
    pub seconds: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExpireRes {
    #[prost(bool, tag = "1")]
    pub is_changed: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExpireatRes {
    #[prost(bool, tag = "1")]
    pub is_changed: bool,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExpiretimeRes {
    #[prost(int64, tag = "1")]
    pub unix_sec: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EchoRes {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ExistsRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HandshakeRes {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetRes {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetexRes {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetsetRes {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetdelRes {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DelRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FlushdbRes {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeysRes {
    #[prost(string, repeated, tag = "1")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IncrRes {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DecrRes {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct IncrbyRes {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DecrbyRes {
    #[prost(int64, tag = "1")]
    pub value: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZElement {
    #[prost(int64, tag = "1")]
    pub score: i64,
    #[prost(string, tag = "2")]
    pub member: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub rank: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZrangeRes {
    #[prost(message, repeated, tag = "1")]
    pub elements: ::prost::alloc::vec::Vec<ZElement>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZpopmaxRes {
    #[prost(message, repeated, tag = "1")]
    pub elements: ::prost::alloc::vec::Vec<ZElement>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZremRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZpopminRes {
    #[prost(message, repeated, tag = "1")]
    pub elements: ::prost::alloc::vec::Vec<ZElement>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ZrankRes {
    #[prost(message, optional, tag = "2")]
    pub element: ::core::option::Option<ZElement>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZcardRes {
    #[prost(int64, tag = "1")]
    pub count: i64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZrangewatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZcountwatchRes {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ZcardwatchRes {}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Status {
    Ok = 0,
    Err = 1,
}
impl Status {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Ok => "OK",
            Self::Err => "ERR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OK" => Some(Self::Ok),
            "ERR" => Some(Self::Err),
            _ => None,
        }
    }
}
